compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0  # will be overridden by environment variables
main_process_ip: null  # will be overridden by environment variables
main_process_port: 29500
main_training_function: main
mixed_precision: fp16
num_machines: 2  # 2 nodes
num_processes: 8  # total of 8 GPUs (assuming 4 GPUs per node)
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
