compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0  # 会被环境变量覆盖
main_process_ip: null  # 会被环境变量覆盖
main_process_port: 29500
main_training_function: main
mixed_precision: fp16
num_machines: 2  # 2个节点
num_processes: 8  # 总共8个GPU (假设每个节点4个GPU)
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
